name: Create repo diagram
on:
  workflow_dispatch: { }
  push:
    branches:
      - v2-mst-aptd-at-lcz-sty
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github,.next,.storybook,docs,public,scripts,svg-to-react"
